In [1]:
import numpy as np

In [2]:
l=[2,3,45,'tushar']

In [3]:
l

[2, 3, 45, 'tushar']

In [4]:
np.array(l)

array(['2', '3', '45', 'tushar'], dtype='<U11')

In [5]:
type(np.array(l))

numpy.ndarray

In [6]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [8]:
np.mat([1,2,3])

matrix([[1, 2, 3]])

In [9]:
np.array([[1,2,3]],ndmin=10)

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [12]:
np.mat([1,3,4,4])

matrix([[1, 3, 4, 4]])

In [14]:
arr=np.array([3,4,5,6])

In [15]:
arr

array([3, 4, 5, 6])

In [16]:
arr[0]

3

In [17]:
arr[2]

5

In [19]:
arr=np.array([[1,2],[3,4]])

In [20]:
arr

array([[1, 2],
       [3, 4]])

In [21]:
arr[1][1]

4

In [22]:
arr=np.array([[1,2],[3,4],[3,7]])

In [23]:
arr

array([[1, 2],
       [3, 4],
       [3, 7]])

In [26]:
arr[2][1]

7

In [27]:
arr[2,1]

7

In [29]:
np.asarray([1,2,3,4],dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [30]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [31]:
np.asanyarray(np.mat([1,2,3,4]))

matrix([[1, 2, 3, 4]])

In [32]:
np.fromfunction(lambda i,j :i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [33]:
np.fromfunction(lambda i,j :i+j,(3,3),dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [35]:
np.fromfunction(lambda i,j,k :i+j+k,(3,3,2),dtype=int)

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]]])

In [39]:
np.fromiter([1,2,3,4,5],dtype=int)

array([1, 2, 3, 4, 5])

In [42]:
np.fromstring('22 45 675 3',sep=' ')

array([ 22.,  45., 675.,   3.])

In [43]:
l=[1,2,3,45,6]

In [44]:
arr=np.array(l)

In [45]:
arr

array([ 1,  2,  3, 45,  6])

In [46]:
arr.ndim

1

In [47]:
arr.size

5

In [48]:
arr.shape

(5,)

In [51]:
arr.dtype

dtype('int32')

In [55]:
list(range(0,5.9))

TypeError: 'float' object cannot be interpreted as an integer

In [58]:
np.arange(0,4.6,.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [63]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [64]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [67]:
np.ones((4,3))+1

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [70]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
np.random.rand(1000,4)

array([[0.7078528 , 0.7277274 , 0.23006278, 0.20565662],
       [0.19045224, 0.49208325, 0.3226778 , 0.91913525],
       [0.87147679, 0.16842193, 0.69228366, 0.68545343],
       ...,
       [0.23155514, 0.36504011, 0.20047006, 0.38628361],
       [0.11580535, 0.07826728, 0.25126772, 0.25507354],
       [0.91097148, 0.24350968, 0.86082534, 0.79485479]])

In [77]:
np.random.randn(4,5)

array([[-1.59059627,  0.88258808,  0.03300831, -0.84238527,  0.87606408],
       [-1.0478634 ,  0.32594335,  0.06462053, -1.19991311, -1.37588818],
       [-0.22327521,  0.30493887, -0.72770069, -1.77838396,  0.25678083],
       [-1.22557681,  0.92619846,  0.21121638,  1.92952555,  0.46479816]])

In [79]:
np.random.randint(3,40,size=50)

array([ 8, 37, 27,  3, 20, 32, 22,  4, 23,  8, 10, 32, 14, 10, 29,  8, 38,
       19, 12, 24, 10, 17, 36, 15,  4, 19, 12, 38,  4,  6, 21, 23,  5,  4,
       27, 33, 18, 31, 16, 37, 18, 17, 28, 36, 34, 31, 26, 27,  9, 38])